name: Generate README.md
on:
  push:
    branches: ["**"]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          path: ${{ github.workspace }}
          name: checkout
          include-hidden-files: true

  generate:
    needs: checkout
    runs-on: ubuntu-latest
    container:
      image: gidoichi/r-rmd:v4.5.2-xpectr@sha256:9afcb157b5228c4b0708131c79c9b3b6257764dcbf321ee7e1a05035ecc1a537
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: checkout
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - name: Build binary
        run: go build
      - name: Generate README.md
        run: R -q -e 'knitr::knit("README.Rmd")'
      - name: Remove binary
        run: rm ./ical-converter
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          path: ${{ github.workspace }}
          name: generate
          include-hidden-files: true

  no-diff:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: generate
      - run: git diff --exit-code --color

  pull-request:
    needs: no-diff
    if: ${{ failure() && needs.no-diff.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: generate
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          branch: create-pull-request/patch/gendocs
          commit-message: "[skip ci] [create-pull-request] automated change"
          delete-branch: true
          token: ${{ secrets.GH_PAT_FOR_CREATE_PULL_REQUEST_ACTION }}
