name: Generate
on:
  push:
    branches: ["**"]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}
          name: checkout

  generate-docs:
    needs: checkout
    runs-on: ubuntu-latest
    container:
      image: gidoichi/r-rmd:v4.3.0-xpectr
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: checkout
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Generate README.md
        run: R -q -e 'knitr::knit("README.Rmd")'
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}
          name: generate

  no-diff:
    needs: generate-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: generate
      - run: git diff --exit-code --color

  pull-request:
    needs: no-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: generate
      - name: Check branch exists
        id: check
        run: |
          set -eux
          if git branch origin "${{ github.ref }}" >/dev/null; then
            echo "exist=true" >> $GITHUB_OUTPUT
          else
            echo "exist=false" >> $GITHUB_OUTPUT
          fi
      - uses: peter-evans/create-pull-request@v6
        if: ${{ jobs.check.outputs.status == 'true' }}
        with:
          branch: create-pull-request/patch/gendocs
          commit-message: "[skip ci] [create-pull-request] automated change"
          delete-branch: true
          token: ${{ secrets.GH_PAT_FOR_CREATE_PULL_REQUEST_ACTION }}
