name: Publish Container
on:
  pull_request:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: dockerhub
      url: https://hub.docker.com/layers/${{ github.repository }}/${{ github.ref_name }}/images/sha256-${{ steps.sha256.outputs.digest }}
    steps:
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        id: docker
        with:
          push: true
          tags: |
            ${{ inputs.tag != '' && format('{0}:{1}', github.repository, inputs.tag) || '' }}
            ${{ github.repository }}:latest
      - id: sha256
        env:
          digest: ${{ steps.docker.outputs.digest }}
        run: echo "digest=${digest#sha256:}" >> "$GITHUB_OUTPUT"
