name: Publish container image
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: dockerhub
      url: https://hub.docker.com/layers/gidoichi/ical-converter/${{ github.ref_name }}/images/sha256-${{ steps.sha256.outputs.digest }}
    steps:
      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        id: docker
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }},${{ github.repository }}:latest
      - id: sha256
        env:
          digest: ${{ steps.docker.outputs.digest }}
        run: echo "digest=${digest#sha256:}" >> "$GITHUB_OUTPUT"
