name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  container:
    runs-on: ubuntu-latest
    environment:
      url: https://hub.docker.com/layers/gidoichi/ical-converter/${{ github.ref_name }}/images/sha256-${{ steps.deployment.outputs.digest }}
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }},${{ github.repository }}:latest
