name: Publish container image
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: dockerhub
      url: https://hub.docker.com/layers/gidoichi/ical-converter/${{ github.ref_name }}/images/sha256-${{ steps.sha256.outputs.digest }}
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        id: docker
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }},${{ github.repository }}:latest
      - id: sha256
        env:
        - digest: ${{ steps.docker.outputs.digest }}
        run: echo "::set-output name=digest::${digest#sha256:}"
