name: Tag
on:
  push:
    branches: ["main"]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT_FOR_RELEASE }}
      - name: Semantic Release
        uses: cocogitto/cocogitto-action@v4
        with:
          command: bump
          args: --auto --disable-bump-commit
