name: Plan
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v4
  terraform-plan:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github
    steps:
      - run: terraform init
      - run: terraform plan -detailed-exitcode
        env:
          TF_VAR_GITHUB_TOKEN: ${{ secrets.TERRAFORM_PLANNER_GITHUB_TOKEN }}
