name: Plan
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
  terraform-plan:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: terraform init
        working-directory: github
      - run: terraform plan -detailed-exitcode
        working-directory: github
        env:
          TF_VAR_GITHUB_TOKEN: ${{ secrets.TERRAFORM_PLANNER_GITHUB_TOKEN }}
